# Generated by Django 4.0.6 on 2022-08-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('F', 'FEMALE'), ('M', 'MALE'), ('O', 'OTHER')], max_length=1)),
            ],
        ),
    ]
